replicaCount: 1
vault:
  address: http://vault-vault.vault:8200
consul:
  address: http://consul-consul.vault:8500
  backup_interval: 86400
aws:
  s3_bucket:
  s3_region: us-east-1

image:
  repository: celliott/consul-bu
  tag: latest
  pullPolicy: Always
service:
  name: consul-bu
  type: ClusterIP
  externalPort: 3000
  internalPort: 3000
ingress:
  enabled: false
  hostname:
  tls:
    enabled: true
resources:
  limits:
    cpu: 200m
    memory: 250m
  requests:
    cpu: 200m
    memory: 250m
